### ISSUE TITLE
Unexpected import syntax

### ISSUE THREAD

**Issue by alex5nader** [LucentFlux/include-wgsl-oil#13]
I just found this crate and it seems great for my use case, but I had some difficulty getting imports to work when porting my shaders. I previously used naga_oil's direct item imports, `#import module::item`, but this syntax was not accepted just by adding `.wgsl` to the module name (`#import module.wgsl::item`).

After looking through the source, I found the regex used to find imports is actually looking for `#import module.wgsl item`. It would be nice if this was the same syntax as regular naga_oil, or if the different syntax is necessary, it would be nice to have a note about this in the README.

**Comment by Joeoc2001** [comment]
The direct naga-oil import syntax was added since the import logic in this crate was written - I'll see if I can find some time in the next few days to allow the richer import forms.

**Comment by alex5nader** [comment]
No worries! I can open a PR if that'd be easier. From when I was looking it should be pretty minor changes.

**Comment by Joeoc2001** [comment]
That'd be great!
